<?php
/**
 * Barbanet_SampleModule
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Barbanet
 * @package    Barbanet_SampleModule
 * @copyright  Copyright (c) 2015-2017 Damián Culotta. (http://www.damianculotta.com.ar/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<h1><?php echo __('My first basic block with custom template.') ?></h1>
<p><?php echo __('This is a dummy block.') ?></p>
<p><?php echo $block->getDummyString(); ?></p>
<ul>
    <li>First item</li>
    <li>Second item</li>
</ul>